const data = {
  "months": [
    {"number": 1, "kanji": "一月", "kana": "いちがつ"},
    {"number": 2, "kanji": "二月", "kana": "にがつ"},
    {"number": 3, "kanji": "三月", "kana": "さんがつ"},
    {"number": 4, "kanji": "四月", "kana": "しがつ"},
    {"number": 5, "kanji": "五月", "kana": "ごがつ"},
    {"number": 6, "kanji": "六月", "kana": "ろくがつ"},
    {"number": 7, "kanji": "七月", "kana": "しちがつ"},
    {"number": 8, "kanji": "八月", "kana": "はちがつ"},
    {"number": 9, "kanji": "九月", "kana": "くがつ"},
    {"number": 10, "kanji": "十月", "kana": "じゅうがつ"},
    {"number": 11, "kanji": "十一月", "kana": "じゅういちがつ"},
    {"number": 12, "kanji": "十二月", "kana": "じゅうにがつ"}
  ],
  "days": [
    {"number": 1, "kanji": "一日", "kana": "ついたち","spday":true},
    {"number": 2, "kanji": "二日", "kana": "ふつか","spday":true},
    {"number": 3, "kanji": "三日", "kana": "みっか","spday":true},
    {"number": 4, "kanji": "四日", "kana": "よっか","spday":true},
    {"number": 5, "kanji": "五日", "kana": "いつか","spday":true},
    {"number": 6, "kanji": "六日", "kana": "むいか","spday":true},
    {"number": 7, "kanji": "七日", "kana": "なのか","spday":true},
    {"number": 8, "kanji": "八日", "kana": "ようか","spday":true},
    {"number": 9, "kanji": "九日", "kana": "ここのか","spday":true},
    {"number": 10, "kanji": "十日", "kana": "とおか","spday":true},
    {"number": 11, "kanji": "十一日", "kana": "じゅういちにち"},
    {"number": 12, "kanji": "十二日", "kana": "じゅうににち"},
    {"number": 13, "kanji": "十三日", "kana": "じゅうさんにち"},
    {"number": 14, "kanji": "十四日", "kana": "じゅうよっか"},
    {"number": 15, "kanji": "十五日", "kana": "じゅうごにち"},
    {"number": 16, "kanji": "十六日", "kana": "じゅうろくにち"},
    {"number": 17, "kanji": "十七日", "kana": "じゅうしちにち"},
    {"number": 18, "kanji": "十八日", "kana": "じゅうはちにち"},
    {"number": 19, "kanji": "十九日", "kana": "じゅうくにち"},
    {"number": 20, "kanji": "二十日", "kana": "はつか","spday":true},
    {"number": 21, "kanji": "二十一日", "kana": "にじゅういちにち"},
    {"number": 22, "kanji": "二十二日", "kana": "にじゅうににち"},
    {"number": 23, "kanji": "二十三日", "kana": "にじゅうさんにち"},
    {"number": 24, "kanji": "二十四日", "kana": "にじゅうよっか"},
    {"number": 25, "kanji": "二十五日", "kana": "にじゅうごにち"},
    {"number": 26, "kanji": "二十六日", "kana": "にじゅうろくにち"},
    {"number": 27, "kanji": "二十七日", "kana": "にじゅうしちにち"},
    {"number": 28, "kanji": "二十八日", "kana": "にじゅうはちにち"},
    {"number": 29, "kanji": "二十九日", "kana": "にじゅうくにち"},
    {"number": 30, "kanji": "三十日", "kana": "さんじゅうにち"},
    {"number": 31, "kanji": "三十一日", "kana": "さんじゅういちにち"}
  ]
}
